name: Build the project

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        # https://github.com/actions/setup-java#usage
        with:
          java-version: "21"
          distribution: "zulu"
          cache: "maven"

      - name: Build the project
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -DskipTests -Dmatchbox.version=3.9.13 site
