name: Build the project

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout matchbox
        uses: actions/checkout@v3

      - name: Setup Java 20
        uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#usage
        with:
          java-version: "20"
          distribution: "zulu"
          cache: "maven"

      - name: Build the project
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -DskipTests -Dmatchbox.version=3.5.2 compile
